// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCihd7f7qjwwmcfJcXbElTpibs4ovpHXd4',
    appId: '1:849941004294:web:4e451ca1228d13e1f6c387',
    messagingSenderId: '849941004294',
    projectId: 'milliondollarway-fbdaf',
    authDomain: 'milliondollarway-fbdaf.firebaseapp.com',
    storageBucket: 'milliondollarway-fbdaf.firebasestorage.app',
    measurementId: 'G-WL5KTJBXWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoWiNb48C2FuXkXbSIrJHuy6x7y5KadOg',
    appId: '1:849941004294:android:7e76f4097af0e548f6c387',
    messagingSenderId: '849941004294',
    projectId: 'milliondollarway-fbdaf',
    storageBucket: 'milliondollarway-fbdaf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByGnniejpwdDUTqrEY7YHrAXhSWJxbSsA',
    appId: '1:849941004294:ios:1ad672e105a4ffa4f6c387',
    messagingSenderId: '849941004294',
    projectId: 'milliondollarway-fbdaf',
    storageBucket: 'milliondollarway-fbdaf.firebasestorage.app',
    iosBundleId: 'com.example.millionDollarWay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByGnniejpwdDUTqrEY7YHrAXhSWJxbSsA',
    appId: '1:849941004294:ios:1ad672e105a4ffa4f6c387',
    messagingSenderId: '849941004294',
    projectId: 'milliondollarway-fbdaf',
    storageBucket: 'milliondollarway-fbdaf.firebasestorage.app',
    iosBundleId: 'com.example.millionDollarWay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCihd7f7qjwwmcfJcXbElTpibs4ovpHXd4',
    appId: '1:849941004294:web:7eb212298beb535af6c387',
    messagingSenderId: '849941004294',
    projectId: 'milliondollarway-fbdaf',
    authDomain: 'milliondollarway-fbdaf.firebaseapp.com',
    storageBucket: 'milliondollarway-fbdaf.firebasestorage.app',
    measurementId: 'G-CGW007HZ0M',
  );

}